server:
  port: 10001
spring:
  application:
    name: house_producer
  web:
    resources:
      cache:
        period: 60m
management:
  endpoints:
    web:
      exposure:
        include: ["beans", "metrics","info","health"]


kafka:
  bootstrapServers: http://localhost:9092
  schemaRegistryUrl: http://localhost:8081
kafka-producer:
  createHouseTopic: create-house-avro


